#eureka配置
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8180/eureka/

#nacos地址
nacos:
  server-addr: localhost:8848