server:
  port: 8184
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /feign/**
      serviceId: service-feign
    api-b:
      path: /feign1/**
      serviceId: service-feign1

eureka:
  instance:
    hostname: localhost
    metadataMap:
      group: example-service-group
      version: 1.0
      region: dev
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/

nacos:
  server-addr: localhost:8848
