server:
  port: 0
spring:
  application:
    name: provider1
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        msgReceiver:
          destination: testRabbit
          content-type: text/plain # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit
          group: abc

eureka:
  instance:
    hostname: localhost
    metadataMap:
      group: example-service-group
      version: 1.0
      region: dev
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/

nacos:
  server-addr: localhost:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8180/eureka/
