server:
  port: 8182
spring:
  application:
    name: provider1

eureka:
  instance:
    hostname: localhost
    metadataMap:
      group: example-service-group
      version: 1.0
      region: dev
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/

nacos:
  server-addr: localhost:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8180/eureka/
